"""Extract the tester's checklist from a Jira issue description.

Convention expected in the description (Jira wiki markup):

    h3. QA Checklist
    * item one
    * item two

OR a table (generated by this tool after apply):

    || Human/AI || QA Checklist ||
    | 🧑 | 1. item one |
    | 🤖 | 2. AI item — why |

Returns dict {"tester": [...], "ai": [...]} on success,
or None if no checklist section found / empty.

The "tester" list contains items written by the human (🧑 or bullet/plain rows).
The "ai" list contains items previously accepted from AI (🤖 rows).
Callers can use both lists to display provenance correctly.
"""
import re

HEADING_RE = re.compile(r"^\s*(h[1-6]\.|#+)\s*(.+)$", re.IGNORECASE)
BULLET_RE = re.compile(r"^\s*[\*\-]\s+(.+)$")
CHECKLIST_HEADING_RE = re.compile(r"checklist", re.IGNORECASE)

TABLE_ROW_RE = re.compile(r"^\s*\|\s*([^|]*)\s*\|\s*([^|]+)\s*\|.*$")

# Emoji markers for provenance detection
AI_MARKERS = {"🤖", "\U0001f916"}
HUMAN_MARKERS = {"🧑", "\U0001f9d1"}


def _clean_braces(text: str) -> str:
    """Remove surrounding double curly braces if they exist."""
    text = text.strip()
    if text.startswith("{{") and text.endswith("}}"):
        text = text[2:-2].strip()
    return text


def _strip_num(text: str) -> str:
    """Remove leading '1. ' numbering from checklist items."""
    m = re.match(r"^\d+\.\s*(.+)$", text)
    return m.group(1).strip() if m else text


def extract_checklist(description: str):
    """Return {"tester": [...], "ai": [...]} or None."""
    if not description:
        return None
    collecting = False
    tester_items = []
    ai_items = []

    for line in description.splitlines():
        heading_match = HEADING_RE.match(line)
        if heading_match:
            collecting = bool(CHECKLIST_HEADING_RE.search(heading_match.group(2)))
            continue
        if "||" in line and CHECKLIST_HEADING_RE.search(line):
            collecting = True
            continue
        if collecting:
            # 1. Try parsing as a table row: | Human/AI | item text |
            row_match = TABLE_ROW_RE.match(line)
            if row_match:
                who_col = row_match.group(1).strip()
                check_text = _clean_braces(_strip_num(row_match.group(2).strip()))
                # Detect provenance from the Human/AI column
                if any(marker in who_col for marker in AI_MARKERS):
                    # Strip trailing "— why" explanation that was appended on apply
                    # Format: "item text — why reason"
                    # We keep the full text so the LLM sees it as already covered
                    ai_items.append(check_text)
                else:
                    tester_items.append(check_text)
                continue

            # 2. Try parsing as a bullet item (plain format, all go to tester)
            bullet_match = BULLET_RE.match(line)
            if bullet_match:
                tester_items.append(_clean_braces(bullet_match.group(1).strip()))
            elif line.strip() == "":
                continue  # blank lines inside the section are fine
            else:
                collecting = False  # non-bullet / non-table-row text ends the section

    all_items = tester_items + ai_items
    if not all_items:
        return None
    return {"tester": tester_items, "ai": ai_items}
